### ISSUE TITLE
Firefox version?

### ISSUE THREAD

**Issue by OveR1337XD** [Spring3/twitch-auto-points#2]
The link to the Firefox addon page is not working.

**Comment by Spring3** [comment]
Oh, thanks for noticing it. Last time it was in review, but I will ask their support about the reason it takes so long. I will let you know here once I get it to the firefox plugin store

**Comment by Spring3** [comment]
@Feky good news - the plugin was approved and the url now points to the correct place. Thanks again for noticing it. 🙇

**Comment by OveR1337XD** [comment]
That's awesome thanks!
